### ISSUE TITLE
Test independence from CRT

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/Handmade-Math#106]
A certain type called `hmm_bool` is of type `int32_t` and imports `stdint.h` to make it work. Oops. 

We should fix this, and find a way to test that adding all math functions actually does allow you to compile it without the CRT or any standard libraries.

**Comment by StrangeZak** [comment]
Most of my projects don’t use the CRT and I simply define HMM_SINF etc to my own. 

Importing stdint.h is fine as it is simply a file that declares data types that guarantee a size for each compiler.

**Comment by bvisness** [comment]
Oh, I didn't realize that. I just recently had a project where using `<stdint.h>` was problematic because I was compiling for a WASM environment without Emscripten or any other compatibility layer, so I guess I conflated those issues. Still, I'm not really sure why it's important to specify the width of `hmm_bool`.

**Comment by StrangeZak** [comment]
I haven’t really looked into it much but every big application defines bools as 32bit wide signed ints. I think it’s just a habit I’ve developed from work

**Comment by StrangeZak** [comment]
Should be fine in WASM now if the SSE path is disabled, removed need for stdint.h.

WASM recently added SIMD (i think) so might be worth trying to get our SSE code to work in WASM.
