### ISSUE TITLE
What is LinearCombineSSE and do we need it?

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/Handmade-Math#109]
I have no idea what it does, and it looks to me like it's mainly used as an implementation helper for multiplication. I'm wondering if it needs to be an actually "public" part of Handmade Math.

**Comment by StrangeZak** [comment]
It’s a helper function we use only for multiplying matrices. I didn’t know that we declared it in the header part of handmade math. That can simply be removed and made a internal (static) function in the implementation portion of the file

**Comment by bvisness** [comment]
Ok. We'll have to see if that will be possible, because it might be used in functions declared as inline, but maybe we can prefix the name with an underscore or something to indicate that it is internal only.

**Comment by StrangeZak** [comment]
Multiplication _shouldnt_ be inlined I think

**Comment by RandyGaul** [comment]
If someone wants to let the compiler inline stuff, they can easily modify the header themselves. It's going to be more important in the long run to keep the header as simple as possible. So I'm in favor of hiding more.

**Comment by RandyGaul** [comment]
P.S. It's doing a [linear combination](https://en.wikipedia.org/wiki/Linear_combination), and was a pretty smart way to implement matrix to vector multiply.
