### ISSUE TITLE
Add ability to change or remove the HMM_ prefix

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/Handmade-Math#112]
We should add the ability to change the function prefixes in case people think HMM_Whatever is too verbose and they can afford to change it in their own project.

Ryan Fleury recommended that we could take an approach like stb_sprintf: https://github.com/nothings/stb/blob/master/stb_sprintf.h#L187-L197

**Comment by StrangeZak** [comment]
Yeah that'd be okay 👍
