### ISSUE TITLE
Orthographic matrix clip plane math wrong?

### ISSUE THREAD

**Issue by Nairou** [HandmadeMath/Handmade-Math#115]
I haven't run tests to see what results I get, but while reading through the implementation of HMM_Orthographic, I noticed that all of the clip plane calculations are doing (Near - Far), rather than (Far - Near). Same for the additions.

I double checked the orthographic projection matrix online, and also cross-checked a couple other math libraries I've used in the past, and they all say (Far - Near). I'm guessing this is a typo?

**Comment by Nairou** [comment]
Actually, thinking more about this, perhaps it's intentional. Most other matrix math libraries are templated, and have right-hand and left-hand versions. Both versions use the same code, but the right-hand version negates the (far-near) calculation. If HandmadeMath is always assuming right-hand coordinates, then (near-far) would get the same result...

**Comment by bvisness** [comment]
Yeah, I believe this all depends on the direction of your z-axis. I'll make sure to keep this in mind for the eventual version of Handmade Math that supports different handedness (see #75).
