### ISSUE TITLE
mat3

### ISSUE THREAD

**Issue by SushilRagoonath** [HandmadeMath/Handmade-Math#123]
Hi, do we have to extend the library if we want a 3x3 matrix and 2x2 matrix?

**Comment by bvisness** [comment]
Yes, at the moment we only have mat4. But I suppose we should consider adding mat2 and mat3; it's not as common for 3D graphics (the focus of this library) but would still be useful to have.

**Comment by SushilRagoonath** [comment]
Understandable,I suppose everything I need in 3d is done with vec3 components.Thanks
