### ISSUE TITLE
User-overridable linkage

### ISSUE THREAD

**Issue by TheSandvichMaker** [HandmadeMath/Handmade-Math#126]
As is, the library exposes certain functions with HMM_EXTERN, without ability for the user to override this. This was a problem for me, so I had to edit the library to make these functions declared as static instead.

STB libraries allow a definition like ```#define HMM_STATIC``` or ```#define HMM_LINKAGE static``` which would allow the user to control whether these symbols get exported without needing to change the source code of the library, and I don't think there's any reason not to support this, it would be a trivial and pleasant addition.

**Comment by StrangeZak** [comment]
Hi,

If I remember correctly at some point this was implemented. But as I can
see it is not anymore. I will reimplement this functionality and get it
pushed for you. Thanks for the suggestion

- Zak

**Comment by StrangeZak** [comment]
Hi, #127 closes this. 

Thanks
