### ISSUE TITLE
 Unnecessary Square Root

### ISSUE THREAD

**Issue by IvoKoller** [HandmadeMath/Handmade-Math#136]
The inverse of a quaternion q is defined as q^-1 == q*/|q|^2, where q^-1 is the quaternion's inverse and q* it's conjugate.
As we know, dot(q, q) _already equals_ |q|^2 so AFAICT there is no need to take the square root _just to then square it again_. So:
```c++
COVERAGE(HMM_InverseQuaternion, 1)
hmm_quaternion HMM_PREFIX(InverseQuaternion)(hmm_quaternion Left)
{
    ASSERT_COVERED(HMM_InverseQuaternion);

    hmm_quaternion Conjugate;
    hmm_quaternion Result;
    float Norm = 0;
    float NormSquared = 0;

    Conjugate.X = -Left.X;
    Conjugate.Y = -Left.Y;
    Conjugate.Z = -Left.Z;
    Conjugate.W = Left.W;

    Norm = HMM_PREFIX(SquareRootF)(HMM_PREFIX(DotQuaternion)(Left, Left));
    NormSquared = Norm * Norm;

    Result = HMM_PREFIX(DivideQuaternionF)(Conjugate, NormSquared);

    return (Result);
}
```
Would become:
``` c++
COVERAGE(HMM_InverseQuaternion, 1)
hmm_quaternion HMM_PREFIX(InverseQuaternion)(hmm_quaternion Left)
{
    ASSERT_COVERED(HMM_InverseQuaternion);
    
    hmm_quaternion Result;

    Result.X = -Left.X;
    Result.Y = -Left.Y;
    Result.Z = -Left.Z;
    Result.W = Left.W;

    Result = HMM_PREFIX(DivideQuaternionF)(Result, (HMM_PREFIX(DotQuaternion)(Left, Left)));

    return (Result);
}
```
I could be missing something here, so please elaborate on why you wrote it that way! 
Anyways, good work so far! :)

**Comment by bvisness** [comment]
No reason that I know of! I suspect I was just following a formula for the quaternion inverse and didn't notice the optimization there.

If you're interested, you can try making this change yourself - if it passes our tests, I'm pretty confident it should be ok. Or I can do it, if you don't have the time or interest. Let me know!

**Comment by IvoKoller** [comment]
I'm working right now, so it'd be awesome if you could do it.

**Comment by IvoKoller** [comment]
@bvisness Alright, tested it and it passes the tests. Not going to bother doing a PR, just copy-paste the code above. Have a nice day!

**Comment by StrangeZak** [comment]
Thanks for the fix
