### ISSUE TITLE
Where's the function to inverse a matrix?

### ISSUE THREAD

**Issue by DeexCoding** [HandmadeMath/Handmade-Math#143]
It's like basic camera stuff. How could you forget this?

**Comment by bvisness** [comment]
See #68. In case you couldn't tell, this library is not under particularly active development, but a decent assortment of matrix inverses is an obvious gap we're aware of that we would add in a 2.0 release.

**Comment by bvisness** [comment]
We will gladly take contributions of course, even to 1.x, as long as it's in line with #68.
