### ISSUE TITLE
Inconsistent use of radians vs. degrees

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/Handmade-Math#31]
The trigonometric functions in Handmade Math use radians for angles. `HMM_Perspective`, on the other hand, uses degrees.

We should make this usage consistent between the two, or find a way to clarify which uses radians and which uses degrees.

**Comment by StrangeZak** [comment]
Oh, i was not aware of this  but i really think degrees, just because i dont want to have to convert what im passing in to a function every single time to radians.

**Comment by StrangeZak** [comment]
@bvisness If you could handle this bug that would be awesome because im not sure of all of the use cases that have this error

**Comment by bvisness** [comment]
As I'm thinking about it more I really don't this this is a big deal, because:

- It is literally just the FOV parameter of `HMM_Perspective` that uses degrees, and that is a case that makes sense to use degrees.
- My gut tells me that the trig functions in a math library should use radians, not degrees
- Changing the trig functions to take degrees instead of radians would be very subtle and difficult to debug across projects that already use Handmade Math.

Or we could just change the FOV parameter to take radians, and then everything would be consistent. Thoughts?

**Comment by StrangeZak** [comment]
I like the FOV the way it is everything else if its fine to you i'd just leave it

**Comment by bvisness** [comment]
Very well then!

**Comment by bvisness** [comment]
Reopening because this continues to bother me and I think it shows up in more places now. (Like HMM_Rotate, which takes an angle in degrees.)

At the very least, we need to name parameters Degrees or Radians depending on what they expect. But I think we should choose a thing and stick to it for all but very special cases (like maybe the FOV of HMM_Perspective).

This seems like a good candidate for a 2.0 release since this would obviously be mega-breaking for people.

**Comment by StrangeZak** [comment]
Do we have a list of what expects radians and what expects to degrees. We can do some sort of analysis then decide on what we want to do here

**Comment by bvisness** [comment]
My analysis:
- Trig functions take radians. 
- HMM_Perspective takes degrees for the FOV and converts to radians during the calculation. 
- HMM_Rotate takes an angle in degrees and converts it to radians during the calculation. 
- HMM_QuaternionFromAxisAngle takes an angle in radians. 

I believe GLM uses degrees for [their perspective matrix](https://glm.g-truc.net/0.9.4/api/a00151.html#ga283629a5ac7fb9037795435daf22560f), although they have a #define that makes it use radians. I regret to inform you that they also use degrees for their rotation matrix. This is stupid and I’m not sure what to do about that. At least they are consistent and appear to use degrees for everything, including their quaternion stuff. 

I still think radians are the more natural choice for everything except perspective FOV (and maybe even for that). For one thing, radians are “correct”. But also, we always have to convert to radians for the actual computation, which is pointless work for a library focused on performance. 

I think we should standardize on radians for everything. Avoid the ambiguity and some unnecessary work.

**Comment by bvisness** [comment]
Maybe it’s worth having a flag for radians vs. degrees for people whose engines use degrees for everything. It should be basically trivial to add a macro to our internal use that converts degrees to radians or does nothing.

**Comment by bvisness** [comment]
Ok yeah, I would like to switch everything to radians by default but add a #define allowing you to use degrees. We could even have the define’s behavior on by default, in a sense, if we wanted to have degrees be the default to match GLM or whatever. (I think the functions should be implemented in radians because the math is all in radians though.)

**Comment by StrangeZak** [comment]
Yep. That sounds like the solution that I would go for. Have everything in radians by default then be able to switch it to degrees if the user wants to via a #define. 

Make sure we document somewhere that GLM uses degrees for everything and if you are coming from GLM to define that flag

**Comment by Nairou** [comment]
It took me quite a while to figure out that HMM_Perspective used degrees rather than radians, as it isn't in the documentation anywhere I could find. So consistency would definitely be nice.

**Comment by Nairou** [comment]
I see activity towards this in #107, is it a HandmadeMath 2.0 thing? Is there a roadmap for that release?

I just had a case yesterday where I calculated an angle with atan2() and then had to convert it to degrees before passing it into HMM_Rotate(), so figured I'd check. :smile:

**Comment by StrangeZak** [comment]
I think if you use the version 2 branch we’re fully radians now. @bvisness can confirm though

**Comment by bvisness** [comment]
Yes, the switch to radians for everything is a 2.0 thing. We don't have a firm roadmap yet, but I think we're nearing a point where we can make one. We do, however, have [a GitHub milestone](https://github.com/HandmadeMath/Handmade-Math/milestone/1) for 2.0 that groups all the tickets we want in a future breaking release - not all of those will be required for 2.0, but all of them are breaking in some way.

I don't recommend working on the 2-dev branch for now, since things are rather in flux.
