### ISSUE TITLE
Alternative implementations for vec4 normalization

### ISSUE THREAD

**Issue by IJzerbaard** [HandmadeMath/Handmade-Math#80]
Normalization could be implemented with rsqrt and a Newton step to get it up to a decent (though not full) accuracy. I have some benchmarks here: http://quick-bench.com/rhPor3bWaoa906sYDP1OA674GXY

However, this is not a clear cut win. For example, the Newton step requires two constants. Calling that function in isolation may not be fast, since those constants may not be in cache. The low-accuracy version does not have that problem, but it has a significantly lower accuracy. The version with Newton step is not 100% accurate but should be acceptable for regular use.

Furthermore, the actual improvement depends quite strongly on the microarchitecture it is being run on. For example, on Nehalem the division and square root take approximately forever and are not pipelined to any significant degree, so sqrt+div is horrible. On the other hand both rqsrt and mulps used to have a lower latency. Starting with Broadwell, sqrt+div is not quite so bad any more. For example on Skylake, a single precision square root (vector or scalar) takes 12 cycles but can be performed once every 3 cycles, on an old Core2 65nm it could take anywhere between 6 and 29 cycles depending on how "nice" the input was (powers of 2 are nice, typical input is not nice) and the next square root could start one cycle before the last square root is done. Scalar square root is usually no better than vector square root, except on Broadwell and some AMD processors - so for a few specific processor it would be better to compute a scalar and shuffle it into all lanes, but for everything else it's better to just redundantly compute 4 equal square roots just to save the shuffle.

In short, on a new Intel processor, rsqrt and a Newton step (which costs 4 multiplications and a subtraction) still has a better throughput than sqrt+div, but the difference is nowhere near as big as it used to be. The latency has become about the same. So it can still help to do rsqrt and a Newton step but it's mainly good for Haswell and older, otherwise it's only a small improvement.

I'm not sure why normalizing the zero vector to zero is necessary, but I've kept that in. Obviously this costs time, but not that much.

Something that would help a lot more is an SoA version of normalize, that normalizes 4 vectors simultaneously and the 4 vectors are stored per-coordinate instead of per-vector. This would allow using a square root and division (or rsqrt and Newton step) to its full potential, with 4 different vector lengths in the 4 lanes. That would allow normalizing 4 vectors at about the same cost that 1 vector costs now (with 3 extra multiplications of course, OTOH no shuffles). But there is no SoA stuff in HMM at all so it seems somewhat out of place.

Here's a benchmark that includes an SoA version as well: http://quick-bench.com/goExus65xkv04_I7OXf9QtMk_uM

**Comment by bvisness** [comment]
Sorry for taking a look at this so late. This is all interesting, but it doesn't sound like the performance gains are enough to offset the extra complexity (and caveats) this would add. However, I found some interesting stuff while digging into this, which you can see over at issue #87.

Thanks for submitting this!
