### ISSUE TITLE
HMM_LookAt Using/Returning Partially Uninitialized Matrix

### ISSUE THREAD

**Issue by ryanfleury** [HandmadeMath/Handmade-Math#83]
Hi there. I was struggling to debug an issue and traced it back to `HMM_LookAt`...

The issue has been marked below with comments.

	
    hmm_mat4 Result; // uninitialized    

    hmm_vec3 F = HMM_NormalizeVec3(HMM_SubtractVec3(Center, Eye));
    hmm_vec3 S = HMM_NormalizeVec3(HMM_Cross(F, Up));
    hmm_vec3 U = HMM_Cross(S, F);

    Result.Elements[0][0] = S.X;
    Result.Elements[0][1] = U.X;
    Result.Elements[0][2] = -F.X;
    // not setting the element at [0][3]

    Result.Elements[1][0] = S.Y;
    Result.Elements[1][1] = U.Y;
    Result.Elements[1][2] = -F.Y;
    // (or at [1][3])

    Result.Elements[2][0] = S.Z;
    Result.Elements[2][1] = U.Z;
    Result.Elements[2][2] = -F.Z;
    // (or [2][3])

    Result.Elements[3][0] = -HMM_DotVec3(S, Eye);
    Result.Elements[3][1] = -HMM_DotVec3(U, Eye);
    Result.Elements[3][2] = HMM_DotVec3(F, Eye);
    Result.Elements[3][3] = 1.0f;
    
    // result returned without initializing the totality of the bottom row
    return (Result);

It was fixed by initializing `Result` to `HMM_Mat4d(1.f)`, but am unsure how you'd like to solve this particularly (it's probably better to just directly write to those elements that weren't initialized).

**Comment by bvisness** [comment]
I swear I fixed that before...sorry about that. Fix version incoming.

**Comment by ryanfleury** [comment]
No worries! Thanks for the quick response :)
