### ISSUE TITLE
Quaternion from Mat4?

### ISSUE THREAD

**Issue by Nairou** [HandmadeMath/Handmade-Math#85]
Is there a way to use a LookAt function and end up with a quaternion? I know HMM_LookAt gives you a mat4, but I don't see a way to convert a mat4 to a quaternion.

Ultimately, I'm trying to find a way to construct a quaternion and specify it's Up vector. LookAt seems to be the only available function that does that.

**Comment by bvisness** [comment]
No, you're right. I think we should have a LookAt for quaternions. I'll get back to you on that one...

**Comment by StrangeZak** [comment]
Something interesting i found: 

https://d3cw3dd2w32x2b.cloudfront.net/wp-content/uploads/2015/01/matrix-to-quat.pdf

**Comment by bvisness** [comment]
I guess I could just run a LookAt matrix through that and call it a day...I'll ponder that.

**Comment by RandyGaul** [comment]
Yes, that's a good solution. The pdf you found is quite nice.
