### ISSUE TITLE
Mat4 SSE definition looks row-major

### ISSUE THREAD

**Issue by bvisness** [HandmadeMath/Handmade-Math#90]
Our definition of hmm_mat4 has an SSE variable called `Rows`. This should really be `Columns`, since our matrices are column-major. Apparently we're doing all the math correctly, but we should probably rename the variable to avoid confusion.

@StrangeZak is this ok to do, or am I misunderstanding something about our SSE implementation?

**Comment by StrangeZak** [comment]
Totally okay to do
